// <auto-generated />
namespace OptikaRihoskova.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _202102071640523 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202102071640523));
        
        string IMigrationMetadata.Id
        {
            get { return "202102071720404_202102071640523"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
